# Generated by Django 5.2.16 on 2026-08-03 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('borough', models.CharField(choices=[('manhattan', 'Manhattan'), ('brooklyn', 'Brooklyn'), ('other', 'Other (out of service zone)')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['borough', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('clinic_site', 'Clinic Site'), ('urgent_care_site', 'Urgent Care Site'), ('lab_draw_site', 'Lab Draw / Collection Site'), ('lab_processing_site', 'Lab Processing Site'), ('pharmacy_counter', 'Pharmacy Counter'), ('hospital_dock', 'Hospital Receiving Dock'), ('home_health_office', 'Home Health Office'), ('other', 'Other')], max_length=32)),
                ('address_line1', models.CharField(max_length=200)),
                ('address_line2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(default='New York', max_length=100)),
                ('state', models.CharField(default='NY', max_length=2)),
                ('postal_code', models.CharField(max_length=10)),
                ('borough', models.CharField(choices=[('manhattan', 'Manhattan'), ('brooklyn', 'Brooklyn'), ('other', 'Other (out of service zone)')], max_length=16)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(default='America/New_York', help_text="IANA timezone name used to interpret this facility's receiving hours.", max_length=64)),
                ('access_instructions', models.TextField(blank=True, help_text='Operational access notes for couriers, e.g. entrance/loading-dock guidance.')),
                ('verification_requirements', models.TextField(blank=True, help_text='Operational verification steps required at handoff, e.g. photo ID check-in at a front desk. Never a clinical/diagnostic requirement.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='organizations.organization')),
                ('service_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='facilities.servicezone')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='facilities.facility')),
            ],
            options={
                'ordering': ['facility__name', '-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FacilityReceivingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_closed', models.BooleanField(default=False, help_text='If true, this facility does not receive deliveries on this day.')),
                ('opens_at', models.TimeField(blank=True, null=True)),
                ('closes_at', models.TimeField(blank=True, null=True)),
                ('same_day_cutoff_time', models.TimeField(blank=True, help_text='Latest local time a same-day pickup/delivery request is accepted for this day.', null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_rules', to='facilities.facility')),
            ],
            options={
                'ordering': ['facility__name', 'day_of_week'],
                'constraints': [models.UniqueConstraint(fields=('facility', 'day_of_week'), name='unique_receiving_rule_per_facility_per_day')],
            },
        ),
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_facility_name_per_org'),
        ),
    ]
