# Generated by Django 5.2.16 on 2026-08-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_courier',
            field=models.BooleanField(default=False, help_text='True for MedRelay couriers (see apps.couriers.CourierProfile). This flag alone grants no access and carries no onboarding/eligibility data itself — see apps.couriers.models and apps.couriers.eligibility.'),
        ),
    ]
