# Generated by Django 5.2.16 on 2026-08-04 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(help_text='An apps.reporting.reports.ReportType value.', max_length=32)),
                ('export_format', models.CharField(choices=[('csv', 'CSV'), ('html', 'HTML')], max_length=8)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('params_hash', models.CharField(help_text='sha256 of (report_type, export_format, sorted params) — the dedup key, scoped per organization.', max_length=64)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['organization', 'report_type', 'export_format', 'params_hash'], name='reporting_e_organiz_f8759a_idx')],
            },
        ),
    ]
