# Generated by Django 5.2.16 on 2026-08-04 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0006_temperatureprofile_max_temp_c_and_more'),
        ('deliveries', '0002_seed_pricing_rules'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(editable=False, help_text="1-based position within this delivery's hash chain.")),
                ('event_type', models.CharField(choices=[('request_created', 'Request Created'), ('package_prepared', 'Package Prepared/Attested'), ('courier_assigned', 'Courier Assigned'), ('courier_arrived', 'Courier Arrived'), ('pickup_scan', 'Pickup Scan'), ('condition_verified', 'Condition Verified'), ('custody_accepted', 'Custody Accepted'), ('route_started', 'Route Started'), ('facility_arrival', 'Facility Arrival'), ('recipient_verified', 'Recipient Verified'), ('delivery_scan', 'Delivery Scan'), ('custody_transferred', 'Custody Transferred'), ('delivery_completed', 'Delivery Completed'), ('incident_opened', 'Incident Opened'), ('incident_updated', 'Incident Updated'), ('incident_resolved', 'Incident Resolved'), ('return_initiated', 'Return Initiated'), ('return_completed', 'Return Completed'), ('correction_appended', 'Correction Appended')], max_length=32)),
                ('actor_type', models.CharField(choices=[('customer', 'Customer Organization'), ('courier', 'Courier'), ('internal_ops', 'Internal Operations'), ('recipient', 'Recipient'), ('system', 'System (Automated)')], max_length=16)),
                ('actor_label', models.CharField(blank=True, help_text="Human-readable actor label when no User row applies (e.g. 'system').", max_length=200)),
                ('occurred_at', models.DateTimeField(help_text='When the event actually happened (may differ from recorded_at for offline-captured or backdated events).')),
                ('recorded_at', models.DateTimeField(help_text="When this row was written. Deliberately not auto_now_add — set explicitly by apps.custody.services.record_event before the hash is computed, so the hash can cover it. See apps/custody/hashing.py's module docstring.")),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_description', models.CharField(blank=True, max_length=200)),
                ('device_metadata', models.JSONField(blank=True, default=dict, help_text="e.g. {'user_agent': ..., 'app_version': ...}.")),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured, event-type-specific data. Never diagnosis/clinical/SSN content.')),
                ('previous_hash', models.CharField(blank=True, help_text="The prior event's current_hash (blank for the first event in a delivery's chain).", max_length=64)),
                ('current_hash', models.CharField(editable=False, help_text="SHA-256 hex digest over this event's canonical fields + previous_hash.", max_length=64)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to=settings.AUTH_USER_MODEL)),
                ('correction_of', models.ForeignKey(blank=True, help_text='Set only on CORRECTION_APPENDED events — the original event being corrected. The original row is never mutated; see module docstring.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='custody.custodyevent')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='deliveries.deliveryrequest')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='cargo.package')),
            ],
            options={
                'ordering': ['delivery_request_id', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProofOfPickup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=200)),
                ('sender_role', models.CharField(blank=True, max_length=120)),
                ('signature_data_url', models.TextField(blank=True, help_text='Base64 data: URL PNG from the HTML5 canvas signature pad. Prototype only.')),
                ('typed_signature_name', models.CharField(blank=True, help_text='Typed-name fallback signature.', max_length=200)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs_of_pickup_captured', to=settings.AUTH_USER_MODEL)),
                ('custody_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custody.custodyevent')),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_pickup', to='deliveries.deliveryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RecipientVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(help_text='An apps.deliveries.models.RecipientVerificationMethod value.', max_length=16)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('pin_hash', models.CharField(blank=True, max_length=128)),
                ('pin_generated_at', models.DateTimeField(blank=True, null=True)),
                ('pin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_verification', to='deliveries.deliveryrequest')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_verifications_confirmed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProofOfDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivered_to_name', models.CharField(blank=True, max_length=200)),
                ('signature_data_url', models.TextField(blank=True)),
                ('typed_signature_name', models.CharField(blank=True, max_length=200)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs_of_delivery_captured', to=settings.AUTH_USER_MODEL)),
                ('custody_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='custody.custodyevent')),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proof_of_delivery', to='deliveries.deliveryrequest')),
                ('recipient_verification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs_of_delivery', to='custody.recipientverification')),
            ],
        ),
        migrations.AddConstraint(
            model_name='custodyevent',
            constraint=models.UniqueConstraint(fields=('delivery_request', 'sequence'), name='unique_custody_event_sequence_per_delivery'),
        ),
    ]
