# Generated by Django 5.2.16 on 2026-08-04 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proofofdelivery',
            name='signature_data_url',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(300000, message='Signature image is too large (max 300,000 characters of base64-encoded data).')]),
        ),
        migrations.AlterField(
            model_name='proofofpickup',
            name='signature_data_url',
            field=models.TextField(blank=True, help_text='Base64 data: URL PNG from the HTML5 canvas signature pad. Prototype only.', validators=[django.core.validators.MaxLengthValidator(300000, message='Signature image is too large (max 300,000 characters of base64-encoded data).')]),
        ),
    ]
