# Generated by Django 5.2.16 on 2026-08-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0007_packageconditioncheck_custody_event_and_more'),
        ('deliveries', '0002_seed_pricing_rules'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('recorded_at', models.DateTimeField(help_text='When the (simulated) reading was taken.')),
                ('source', models.CharField(choices=[('simulated', 'Simulated')], default='simulated', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_readings', to='deliveries.deliveryrequest')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_readings', to='cargo.package')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Set only when a human triggered the simulation (e.g. via the admin action or a management command run interactively); blank for an unattended/scheduled run.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_readings_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['delivery_request_id', 'recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TemperatureExcursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature_c', models.DecimalField(decimal_places=1, max_digits=5)),
                ('threshold_min_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('threshold_max_c', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temperature_excursions', to='deliveries.deliveryrequest')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_excursions', to='incidents.incident')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temperature_excursions', to='cargo.package')),
                ('reading', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='excursion', to='temperature.temperaturereading')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
    ]
