"""Canonical serialization + SHA-256 hashing for the `CustodyEvent` tamper-evident chain.

Design decision (docs/CURRENT_STATUS.md "Phase 6" section has the full
write-up): each `CustodyEvent`'s `current_hash` is a real SHA-256 digest
(Python stdlib `hashlib` — no new dependency) computed over a canonical JSON
serialization of that event's own fields, chained to the previous event's
`current_hash` for the same delivery request (blockchain-style, per
delivery). This module is the **single** place that canonicalization/hashing
logic lives — both `apps.custody.services.record_event` (which computes a
new event's `current_hash` at creation time) and
`apps.custody.verification.verify_custody_chain` (which *recomputes* the
expected hash for every existing event to detect tampering) call the exact
same `compute_event_hash` function, so there is no risk of the writer and
the verifier ever silently drifting out of sync with two different hashing
implementations.

What is (and is not) included in the hash: every field that describes what
happened (`delivery_request_id`, `package_id`, `sequence`, `event_type`,
`actor_type`, `actor_user_id`, `actor_label`, `occurred_at`, location,
device metadata, the structured payload, and `correction_of_id`), plus the
chain-link (`previous_hash`) itself. `recorded_at` (when the row was
physically written) is deliberately **not** auto-generated by the database
(`CustodyEvent.recorded_at` has no `auto_now_add=True`) specifically so it
can be computed once, up front, by `apps.custody.services.record_event`
*before* the hash is computed — this keeps hashing fully deterministic and
reproducible from the row's own stored field values, with nothing computed
implicitly by the database at INSERT time that the hash could not see.
`current_hash` itself is obviously excluded (it is the output, not an
input).
"""

from __future__ import annotations

import hashlib
import json
from decimal import Decimal
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from apps.custody.models import CustodyEvent


def _json_default(value: Any) -> Any:
    if isinstance(value, Decimal):
        return str(value)
    if hasattr(value, "isoformat"):
        return value.isoformat()
    return str(value)


def canonical_event_fields(event: CustodyEvent) -> dict[str, Any]:
    """The exact, ordered set of fields hashed for `event`.

    Uses `_id` attribute access (e.g. `delivery_request_id`, not
    `delivery_request`) throughout so this never triggers an extra database
    query to follow a foreign key just to compute a hash, and so the hash is
    defined purely in terms of stored scalar/JSON values.
    """
    return {
        "delivery_request_id": str(event.delivery_request_id),
        "package_id": event.package_id,
        "sequence": event.sequence,
        "event_type": event.event_type,
        "actor_type": event.actor_type,
        "actor_user_id": event.actor_user_id,
        "actor_label": event.actor_label,
        "occurred_at": event.occurred_at,
        "recorded_at": event.recorded_at,
        "location_lat": event.location_lat,
        "location_lng": event.location_lng,
        "location_description": event.location_description,
        "device_metadata": event.device_metadata,
        "payload": event.payload,
        "correction_of_id": (str(event.correction_of_id) if event.correction_of_id else None),
    }


def compute_event_hash(event: CustodyEvent, previous_hash: str) -> str:
    """SHA-256 hex digest of `event`'s canonical fields chained to `previous_hash`.

    `previous_hash` is passed explicitly (rather than read off
    `event.previous_hash`) so the same function can be used both to compute
    a *new* event's hash (before `event.previous_hash` has necessarily been
    assigned) and to *recompute* an existing event's expected hash during
    verification (where `event.previous_hash` is exactly the value that
    should be passed back in — see `apps.custody.verification`).
    """
    canonical_fields = canonical_event_fields(event)
    canonical_json = json.dumps(
        canonical_fields, sort_keys=True, default=_json_default, separators=(",", ":")
    )
    digest_input = f"{previous_hash}|{canonical_json}".encode()
    return hashlib.sha256(digest_input).hexdigest()


__all__ = ["canonical_event_fields", "compute_event_hash"]
