# Generated by Django 5.2.16 on 2026-08-03 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('deliveries', '0002_seed_pricing_rules'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLAProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.CharField(help_text='An apps.deliveries.models.ServiceLevel value.', max_length=16, unique=True)),
                ('min_slack_minutes', models.PositiveIntegerField(help_text="Minimum acceptable buffer (minutes) between the estimated delivery completion and required_delivery_by before a delivery is flagged 'at risk'. Negative slack is always 'infeasible' regardless of this value.")),
                ('description', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['service_level'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('reassigned', 'Reassigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('score_at_assignment', models.DecimalField(blank=True, decimal_places=2, help_text="The candidate's total explainable score (apps.dispatch.scoring) at the moment this assignment was made, kept for audit even if scoring inputs later change.", max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, help_text='The dispatcher (or None for an unattended/automated assignment) who made this assignment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='couriers.courierprofile')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='deliveries.deliveryrequest')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('candidate_count', models.PositiveIntegerField(default=0)),
                ('eligible_count', models.PositiveIntegerField(default=0)),
                ('computed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_recommendations_run', to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_recommendations', to='deliveries.deliveryrequest')),
            ],
            options={
                'ordering': ['-computed_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_type', models.CharField(choices=[('not_top_ranked', 'Chose a non-top-ranked eligible candidate'), ('reassignment', 'Reassignment away from an existing assignment'), ('note', 'Dispatcher note on an otherwise top-ranked choice')], max_length=16)),
                ('reason', models.TextField(help_text='Required — see save() below, never blank.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_overrides_made', to=settings.AUTH_USER_MODEL)),
                ('chosen_courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_overrides_chosen', to='couriers.courierprofile')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_overrides', to='deliveries.deliveryrequest')),
                ('previous_courier', models.ForeignKey(blank=True, help_text='Set only for REASSIGNMENT overrides — the courier being reassigned away from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_overrides_previous', to='couriers.courierprofile')),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='dispatch.dispatchrecommendation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchRecommendationCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('eligible', models.BooleanField()),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('factor_scores', models.JSONField(blank=True, default=dict)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('hard_failure_reasons', models.JSONField(blank=True, default=list)),
                ('eta_to_pickup_minutes', models.DecimalField(decimal_places=1, max_digits=6)),
                ('sla_slack_minutes', models.DecimalField(decimal_places=1, max_digits=9)),
                ('sla_feasibility', models.CharField(max_length=16)),
                ('toll_estimate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_recommendation_candidates', to='couriers.courierprofile')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='dispatch.dispatchrecommendation')),
            ],
            options={
                'ordering': ['recommendation_id', 'rank'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offered', 'Offered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='offered', max_length=16)),
                ('offered_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='couriers.courierprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_job_offers_created', to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='deliveries.deliveryrequest')),
            ],
            options={
                'ordering': ['-offered_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total_duration_minutes', models.DecimalField(decimal_places=1, max_digits=7)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_plans', to='dispatch.deliveryassignment')),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_plan', to='deliveries.deliveryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('leg_type', models.CharField(choices=[('to_pickup', 'Courier to Pickup'), ('pickup_to_destination', 'Pickup to Destination')], max_length=32)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=7)),
                ('duration_minutes', models.DecimalField(decimal_places=1, max_digits=7)),
                ('from_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_legs_from', to='facilities.facility')),
                ('to_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_legs_to', to='facilities.facility')),
                ('route_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='dispatch.routeplan')),
            ],
            options={
                'ordering': ['route_plan_id', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='deliveryassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('delivery_request',), name='unique_active_assignment_per_delivery_request'),
        ),
        migrations.AddConstraint(
            model_name='dispatchrecommendationcandidate',
            constraint=models.UniqueConstraint(fields=('recommendation', 'courier'), name='unique_candidate_per_recommendation'),
        ),
        migrations.AddConstraint(
            model_name='routeleg',
            constraint=models.UniqueConstraint(fields=('route_plan', 'sequence'), name='unique_route_leg_sequence'),
        ),
    ]
