# Generated by Django 5.2.16 on 2026-08-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_seed_sla_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='decline_reason',
            field=models.TextField(blank=True, help_text="Phase 5: optional courier-recorded reason for declining (docs/PRODUCT_REQUIREMENTS.md section 6 — 'Legitimate cargo/safety rejection must be recordable'). Never required; a courier may decline without giving a reason."),
        ),
    ]
