# Generated by Django 5.2.16 on 2026-08-03 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0004_alter_package_description'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applicant', 'Applicant'), ('approved', 'Approved Courier'), ('suspended', 'Suspended Courier'), ('inactive', 'Inactive Courier')], default='applicant', max_length=16)),
                ('identity_review_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_started', max_length=16)),
                ('driver_license_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('valid', 'Valid'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='not_submitted', max_length=16)),
                ('insurance_status', models.CharField(choices=[('not_submitted', 'Not Submitted'), ('pending_review', 'Pending Review'), ('valid', 'Valid'), ('expired', 'Expired'), ('rejected', 'Rejected')], default='not_submitted', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('notes', models.TextField(blank=True, help_text='Internal operational notes only. Never a diagnosis/clinical/SSN/ID-number.')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('home_service_zone', models.ForeignKey(blank=True, help_text="The courier's default/home service zone, used as an eligibility fallback when no current CourierAvailability.current_service_zone is set.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_couriers', to='facilities.servicezone')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='CourierCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('driver_license', 'Driver License'), ('insurance', 'Insurance'), ('identity_verification', 'Identity Verification'), ('background_check_placeholder', 'Background Check (Placeholder — No Real Provider Integrated)'), ('other', 'Other')], max_length=32)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending_review', max_length=16)),
                ('issued_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_reference', models.CharField(blank=True, help_text="Placeholder reference only (e.g. a synthetic filename/label such as 'synthetic-drivers-license-demo.pdf') — never a real uploaded document or a real identity-document number. This prototype never stores real sensitive documents.", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Typically a courier_onboarding_reviewer or compliance_reviewer internal user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_courier_credentials', to=settings.AUTH_USER_MODEL)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='couriers.courierprofile')),
            ],
            options={
                'ordering': ['courier__user__username', 'credential_type'],
            },
        ),
        migrations.CreateModel(
            name='CourierAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('shift_start', models.TimeField(blank=True, help_text='Local shift start time (facility-local, America/New_York). Blank means no shift restriction while online.', null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('max_concurrent_deliveries', models.PositiveIntegerField(default=1, help_text='Configured capacity limit. Phase 3 has no DeliveryAssignment model yet, so current workload is always treated as 0 — see apps.couriers.eligibility.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_service_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='couriers_currently_here', to='facilities.servicezone')),
                ('courier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='couriers.courierprofile')),
            ],
            options={
                'verbose_name_plural': 'Courier availability',
                'ordering': ['courier__user__username'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('insulated_container', 'Insulated Container'), ('refrigerated_container', 'Refrigerated Container'), ('cooler_with_ice_packs', 'Cooler with Ice Packs'), ('lockbox', 'Lockbox'), ('ppe_kit', 'PPE Kit'), ('other', 'Other')], max_length=32)),
                ('supports_refrigeration', models.BooleanField(default=False, help_text="True if this equipment provides refrigerated capability, used by the 'vehicle/equipment incompatible' hard-eligibility filter.")),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='couriers.courierprofile')),
            ],
            options={
                'verbose_name_plural': 'Equipment',
                'ordering': ['courier__user__username', 'equipment_type'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(choices=[('general_orientation', 'General Orientation'), ('cargo_handling', 'Cargo Handling'), ('cold_chain_handling', 'Cold Chain Handling'), ('safety', 'Safety'), ('other', 'Other')], max_length=32)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='couriers.courierprofile')),
            ],
            options={
                'ordering': ['courier__user__username', 'training_type'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('van', 'Van'), ('motorcycle', 'Motorcycle'), ('bicycle', 'Bicycle'), ('on_foot', 'On Foot'), ('other', 'Other')], max_length=16)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('plate_number', models.CharField(blank=True, help_text='Synthetic placeholder plate/registration string only — never a real plate.', max_length=32)),
                ('supports_refrigeration', models.BooleanField(default=False, help_text="True if this vehicle itself provides refrigerated capability (e.g. a built-in cold box), used by the 'vehicle/equipment incompatible' hard-eligibility filter.")),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='couriers.courierprofile')),
            ],
            options={
                'ordering': ['courier__user__username'],
            },
        ),
        migrations.CreateModel(
            name='CargoAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supports_refrigeration', models.BooleanField(default=False, help_text='True if the courier is authorized to handle this cargo class under refrigerated conditions, not just ambient.')),
                ('is_active', models.BooleanField(default=True)),
                ('authorized_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_cargo_authorizations', to=settings.AUTH_USER_MODEL)),
                ('cargo_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courier_authorizations', to='cargo.cargoclass')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_authorizations', to='couriers.courierprofile')),
            ],
            options={
                'ordering': ['courier__user__username', 'cargo_class__code'],
                'constraints': [models.UniqueConstraint(fields=('courier', 'cargo_class'), name='unique_cargo_authorization_per_courier_per_class')],
            },
        ),
    ]
