# Generated by Django 5.2.16 on 2026-08-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierActionIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text="Logical endpoint name, e.g. 'job_offer_accept', 'delivery_status_advance', 'location_ping'.", max_length=64)),
                ('key', models.CharField(help_text='Client-generated Idempotency-Key value.', max_length=255)),
                ('response_data', models.JSONField(blank=True, default=dict, help_text='The stored successful response, replayed on retry.')),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_idempotency_keys', to='couriers.courierprofile')),
            ],
            options={
                'verbose_name': 'Courier action idempotency key',
                'verbose_name_plural': 'Courier action idempotency keys',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('courier', 'endpoint', 'key'), name='unique_courier_action_idempotency_key')],
            },
        ),
    ]
