"""Simulated temperature readings and excursions.

**No real IoT/temperature-sensor hardware is integrated in this prototype**
(docs/TECH_STACK_AND_ZERO_COST_POLICY.md's zero-cost policy explicitly
requires external capabilities like "temperature sensors" to go through an
adapter interface with a local/mock implementation — there is no real
`TemperatureSensorProvider` adapter to be a real one for yet, since there is
no real sensor hardware anywhere in this project's demo environment).
`TemperatureReading` rows are always synthetic, generated by
`apps.temperature.services.record_reading` (called directly, or via the
`simulate_temperature_readings` management command) — never a live device
push. See docs/PRODUCT_REQUIREMENTS.md section 12: "indicator/logger
placeholder... no claim of validated cold-chain compliance in the
prototype."
"""

from __future__ import annotations

from django.conf import settings
from django.db import models


class TemperatureReadingSource(models.TextChoices):
    SIMULATED = "simulated", "Simulated"


class TemperatureReading(models.Model):
    """One (always simulated — see module docstring) sensor reading for a
    package in transit."""

    delivery_request = models.ForeignKey(
        "deliveries.DeliveryRequest", on_delete=models.CASCADE, related_name="temperature_readings"
    )
    package = models.ForeignKey(
        "cargo.Package",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="temperature_readings",
    )
    temperature_c = models.DecimalField(max_digits=5, decimal_places=1)
    recorded_at = models.DateTimeField(help_text="When the (simulated) reading was taken.")
    source = models.CharField(
        max_length=16,
        choices=TemperatureReadingSource.choices,
        default=TemperatureReadingSource.SIMULATED,
    )
    recorded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="temperature_readings_recorded",
        help_text="Set only when a human triggered the simulation (e.g. via the admin action or "
        "a management command run interactively); blank for an unattended/scheduled run.",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["delivery_request_id", "recorded_at"]

    def __str__(self) -> str:
        return f"{self.delivery_request_id} @ {self.recorded_at}: {self.temperature_c}C"


class TemperatureExcursion(models.Model):
    """A `TemperatureReading` that fell outside its package's
    `TemperatureProfile` range. Always opens an `Incident`
    (docs/PRODUCT_REQUIREMENTS.md section 12: "excursion opens an incident
    and may place delivery on hold") — see `apps.temperature.services.
    record_reading`, the only place these are created.
    """

    reading = models.OneToOneField(
        TemperatureReading, on_delete=models.CASCADE, related_name="excursion"
    )
    delivery_request = models.ForeignKey(
        "deliveries.DeliveryRequest",
        on_delete=models.CASCADE,
        related_name="temperature_excursions",
    )
    package = models.ForeignKey(
        "cargo.Package",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="temperature_excursions",
    )
    temperature_c = models.DecimalField(max_digits=5, decimal_places=1)
    threshold_min_c = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)
    threshold_max_c = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)
    incident = models.ForeignKey(
        "incidents.Incident",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="temperature_excursions",
    )
    detected_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-detected_at"]

    def __str__(self) -> str:
        return f"Excursion for {self.delivery_request_id}: {self.temperature_c}C"
