# Generated by Django 5.2.16 on 2026-08-03 16:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('facilities', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('base_fee', 'Base fee'), ('per_km_rate', 'Per-kilometer distance rate'), ('per_minute_rate', 'Per-minute time rate'), ('average_speed_kmh', 'Assumed average travel speed (km/h)'), ('same_day_surcharge', 'Same-day service-level surcharge'), ('stat_surcharge', 'STAT service-level surcharge'), ('cargo_class_2_surcharge', 'Class 2 cargo/equipment surcharge'), ('cargo_class_3_surcharge', 'Class 3 cargo/equipment surcharge'), ('refrigerated_surcharge', 'Refrigerated equipment surcharge'), ('after_hours_surcharge', 'After-hours surcharge'), ('inter_borough_toll_estimate', 'Inter-borough toll estimate'), ('wait_time_placeholder_fee', 'Wait-time placeholder fee'), ('return_trip_fee', 'Return-trip fee')], max_length=32, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_level', models.CharField(choices=[('scheduled', 'Scheduled'), ('same_day', 'Same Day'), ('stat', 'STAT')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validation_required', 'Validation Required'), ('ready_for_dispatch', 'Ready for Dispatch'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('courier_en_route_to_pickup', 'Courier En Route to Pickup'), ('at_pickup', 'At Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_destination', 'At Destination'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('incident_hold', 'Incident Hold'), ('returning', 'Returning'), ('returned', 'Returned'), ('failed', 'Failed')], default='draft', max_length=32)),
                ('pickup_window_start', models.DateTimeField()),
                ('pickup_window_end', models.DateTimeField()),
                ('required_delivery_by', models.DateTimeField()),
                ('package_count', models.PositiveIntegerField(default=1)),
                ('approximate_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('approximate_length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('approximate_width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('approximate_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('sender_contact_name', models.CharField(blank=True, max_length=200)),
                ('sender_contact_phone', models.CharField(blank=True, max_length=32)),
                ('sender_contact_role', models.CharField(blank=True, max_length=120)),
                ('recipient_contact_name', models.CharField(blank=True, max_length=200)),
                ('recipient_contact_phone', models.CharField(blank=True, max_length=32)),
                ('recipient_contact_role', models.CharField(blank=True, max_length=120)),
                ('recipient_verification_method', models.CharField(choices=[('none', 'None'), ('pin', 'PIN Code'), ('signature', 'Signature')], default='none', max_length=16)),
                ('facility_instructions', models.TextField(blank=True, help_text='Operational handling notes for couriers/facilities.')),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Not set in Phase 2 — invoicing/billing is Phase 7.', max_digits=8, null=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Optimistic-concurrency version counter.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to='cargo.cargoclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to='organizations.organization')),
                ('temperature_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_requests', to='cargo.temperatureprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStatusTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validation_required', 'Validation Required'), ('ready_for_dispatch', 'Ready for Dispatch'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('courier_en_route_to_pickup', 'Courier En Route to Pickup'), ('at_pickup', 'At Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_destination', 'At Destination'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('incident_hold', 'Incident Hold'), ('returning', 'Returning'), ('returned', 'Returned'), ('failed', 'Failed')], max_length=32)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('validation_required', 'Validation Required'), ('ready_for_dispatch', 'Ready for Dispatch'), ('offered', 'Offered'), ('assigned', 'Assigned'), ('courier_en_route_to_pickup', 'Courier En Route to Pickup'), ('at_pickup', 'At Pickup'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('at_destination', 'At Destination'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('incident_hold', 'Incident Hold'), ('returning', 'Returning'), ('returned', 'Returned'), ('failed', 'Failed')], max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_status_transitions', to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_transitions', to='deliveries.deliveryrequest')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distance_time_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service_level_surcharge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cargo_equipment_surcharge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('toll_estimate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('wait_time_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('after_hours_surcharge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('return_trip_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='deliveries.deliveryrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], max_length=16)),
                ('weekly_days_of_week', models.JSONField(blank=True, default=list, help_text='List of weekday ints (0=Monday..6=Sunday, matching facilities.DayOfWeek). Only meaningful when frequency=weekly.')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Open-ended when blank.', null=True)),
                ('holiday_exceptions', models.JSONField(blank=True, default=list, help_text='Simple list of ISO date strings to skip generation on.')),
                ('service_level', models.CharField(choices=[('scheduled', 'Scheduled'), ('same_day', 'Same Day'), ('stat', 'STAT')], max_length=16)),
                ('is_approved', models.BooleanField(default=False, help_text='Operations-approval flag — required before generation may run.')),
                ('is_paused', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_routes', to='cargo.cargoclass')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_routes', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_routes', to='organizations.organization')),
                ('temperature_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_routes', to='cargo.temperatureprofile')),
            ],
            options={
                'ordering': ['organization__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('destination', 'Destination')], max_length=16)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('scheduled_window_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_window_end', models.DateTimeField(blank=True, null=True)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='deliveries.deliveryrequest')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_stops', to='facilities.facility')),
            ],
            options={
                'ordering': ['delivery_request_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('delivery_request', 'stop_type'), name='unique_stop_type_per_delivery_request')],
            },
        ),
        migrations.CreateModel(
            name='RecurringRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup'), ('destination', 'Destination')], max_length=16)),
                ('instructions', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recurring_route_stops', to='facilities.facility')),
                ('recurring_route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='deliveries.recurringroute')),
            ],
            options={
                'ordering': ['recurring_route_id', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('recurring_route', 'sequence'), name='unique_recurring_route_stop_sequence')],
            },
        ),
    ]
