# Generated by Django 5.2.16 on 2026-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_seed_pricing_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryrequest',
            name='facility_instructions',
            field=models.TextField(blank=True, help_text='Operational handling notes for couriers/facilities.', max_length=2000),
        ),
    ]
