# Generated by Django 5.2.16 on 2026-08-04 14:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0002_seed_pricing_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientLinkAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('viewed', 'Viewed'), ('expired_token_rejected', 'Expired Token Rejected'), ('invalid_token_rejected', 'Invalid Token Rejected'), ('pin_verified', 'PIN Verified'), ('pin_failed', 'PIN Attempt Failed')], max_length=32)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipient_link_accesses', to='deliveries.deliveryrequest')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
