# Generated by Django 5.2.16 on 2026-08-04 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_succeeded', 'Login Succeeded'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('membership_created', 'Organization Membership Created'), ('membership_changed', 'Organization Membership Changed'), ('internal_role_assigned', 'Internal Role Assigned'), ('internal_role_changed', 'Internal Role Changed')], max_length=32)),
                ('actor_label', models.CharField(blank=True, help_text='Fallback identifier when no User row is resolvable (e.g. a failed login attempt against a username that does not exist).', max_length=150)),
                ('summary', models.CharField(help_text='Short, human-readable description. Operational identifiers only, never PHI.', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text="Small structured detail (e.g. {'role': 'owner'}). Never PHI.")),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed or was subject to this event, if resolvable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, help_text='Set for organization-membership events; blank for internal-role/auth events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='organizations.organization')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['-occurred_at'], name='audit_audit_occurre_ccfa85_idx'), models.Index(fields=['event_type', '-occurred_at'], name='audit_audit_event_t_adc3c6_idx')],
            },
        ),
    ]
