# Generated by Django 5.2.16 on 2026-08-03 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0002_courieractionidempotencykey'),
        ('dispatch', '0003_joboffer_decline_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_meters', models.DecimalField(blank=True, decimal_places=2, help_text="Optional — the browser Geolocation API's reported accuracy radius, if given.", max_digits=7, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='dispatch.deliveryassignment')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='couriers.courierprofile')),
            ],
            options={
                'ordering': ['-recorded_at'],
                'indexes': [models.Index(fields=['assignment', '-recorded_at'], name='tracking_co_assignm_51a42b_idx')],
            },
        ),
    ]
