# Generated by Django 5.2.16 on 2026-08-03 16:50

import apps.cargo.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CargoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('class_1', 'Class 1 — Documents & Non-Hazardous Supplies'), ('class_2', 'Class 2 — Approved Routine Specimens'), ('class_3', 'Class 3 — Sealed Non-Controlled Prescription Medication')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cargo classes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PackageIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.cargo.models._generate_package_identifier_code, max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_confirmed', models.BooleanField(default=True, help_text='Sender confirms packaging/sealing/labeling meets MedRelay policy for the class.')),
                ('classification_confirmed', models.BooleanField(default=True, help_text='Sender confirms the declared cargo class accurately reflects package contents.')),
                ('notes', models.TextField(blank=True, help_text='Optional free-text notes. Never diagnosis/clinical content.')),
                ('attested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ambient', 'Ambient'), ('refrigerated', 'Refrigerated')], max_length=16, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CargoPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requires_packaging_attestation', models.BooleanField(default=True)),
                ('allows_ambient', models.BooleanField(default=True)),
                ('allows_refrigerated', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_class', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='cargo.cargoclass')),
            ],
            options={
                'verbose_name_plural': 'Cargo policies',
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_number', models.PositiveIntegerField(default=1, help_text="This package's position within the delivery request's package count.")),
                ('approximate_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('approximate_length_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('approximate_width_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('approximate_height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('description', models.CharField(blank=True, help_text="Short operational description (e.g. 'sealed specimen bag'). Never clinical content.", max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='cargo.cargoclass')),
            ],
            options={
                'ordering': ['delivery_request_id', 'sequence_number'],
            },
        ),
    ]
