# Generated by Django 5.2.16 on 2026-08-03 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0001_initial'),
        ('deliveries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='delivery_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='deliveries.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='packageidentifier',
            name='package',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='identifier', to='cargo.package'),
        ),
        migrations.AddField(
            model_name='packagingattestation',
            name='attested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packaging_attestations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='packagingattestation',
            name='delivery_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='packaging_attestation', to='deliveries.deliveryrequest'),
        ),
        migrations.AddField(
            model_name='package',
            name='temperature_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='cargo.temperatureprofile'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('delivery_request', 'sequence_number'), name='unique_package_sequence_per_delivery_request'),
        ),
    ]
