# Generated by Django 5.2.16 on 2026-08-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_seed_cargo_reference_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.CharField(blank=True, help_text="Short operational description (e.g. 'sealed specimen bag'). Never clinical.", max_length=200),
        ),
    ]
