# Generated by Django 5.2.16 on 2026-08-03 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_package_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='scanned_at',
            field=models.DateTimeField(blank=True, help_text="Phase 5 (courier PWA): when the assigned courier confirmed this package's PackageIdentifier code during pickup (camera QR scan or manual code entry — see apps.cargo.services.confirm_package_scan). This is the physical act of scanning a package at pickup, not the custody/chain-of-custody proof event (recipient PIN/signature capture), which is Phase 6 work — see docs/CURRENT_STATUS.md 'Phase 5' for the exact boundary.", null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='scanned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_packages', to=settings.AUTH_USER_MODEL),
        ),
    ]
