# Generated by Django 5.2.16 on 2026-08-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_package_scanned_at_package_scanned_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='temperatureprofile',
            name='max_temp_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Maximum acceptable temperature (Celsius) for this profile. Blank means no upper bound is enforced.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='temperatureprofile',
            name='min_temp_c',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Minimum acceptable temperature (Celsius) for this profile. Blank means no lower bound is enforced (e.g. ambient).', max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='PackageConditionCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pickup', 'At Pickup'), ('delivery', 'At Delivery')], max_length=16)),
                ('seal_status', models.CharField(choices=[('intact', 'Intact'), ('broken', 'Broken'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=16)),
                ('physical_damage_observed', models.BooleanField(default=False)),
                ('damage_description', models.CharField(blank=True, help_text='Short operational description. Never clinical.', max_length=300)),
                ('temperature_indicator_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('ok', 'Within Range'), ('tripped', 'Tripped/Excursion Indicated'), ('unknown', 'Unknown/Unreadable')], default='not_applicable', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_condition_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['package_id', 'stage'],
            },
        ),
    ]
