# Generated by Django 5.2.16 on 2026-08-04 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_temperatureprofile_max_temp_c_and_more'),
        ('custody', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageconditioncheck',
            name='custody_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='condition_checks', to='custody.custodyevent'),
        ),
        migrations.AddField(
            model_name='packageconditioncheck',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_checks', to='cargo.package'),
        ),
        migrations.AddConstraint(
            model_name='packageconditioncheck',
            constraint=models.UniqueConstraint(fields=('package', 'stage'), name='unique_condition_check_per_package_stage'),
        ),
    ]
