# Generated by Django 5.2.16 on 2026-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_seed_temperature_ranges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagingattestation',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional free-text notes. Never diagnosis/clinical content.', max_length=2000),
        ),
    ]
