# Generated by Django 5.2.16 on 2026-08-03 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('org_type', models.CharField(choices=[('clinic', 'Clinic'), ('urgent_care', 'Urgent Care Center'), ('diagnostic_lab', 'Diagnostic Laboratory'), ('pharmacy', 'Pharmacy'), ('hospital', 'Hospital / Health System'), ('home_health', 'Home Health Organization')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Internal operational notes only. Never diagnosis/clinical/PHI content.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Organization Owner'), ('administrator', 'Administrator'), ('requester_dispatcher', 'Requester / Dispatcher'), ('billing_manager', 'Billing Manager'), ('compliance_reviewer', 'Compliance Reviewer'), ('read_only_auditor', 'Read-only Auditor')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organization__name', 'user__username'],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_membership_per_user_per_org')],
            },
        ),
    ]
