# Generated by Django 5.2.16 on 2026-08-04 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cargo', '0007_packageconditioncheck_custody_event_and_more'),
        ('deliveries', '0002_seed_pricing_rules'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('leak_spill', 'Leak/Spill'), ('broken_seal', 'Broken Seal'), ('package_damage', 'Package Damage'), ('temperature_excursion', 'Temperature Excursion'), ('vehicle_accident', 'Vehicle Accident'), ('courier_injury_exposure', 'Courier Injury/Exposure'), ('lost_package', 'Lost Package'), ('incorrect_recipient', 'Incorrect Recipient'), ('wrong_destination', 'Wrong Destination'), ('missed_sla', 'Missed SLA'), ('recipient_unavailable', 'Recipient Unavailable'), ('suspected_tampering', 'Suspected Tampering')], max_length=32)),
                ('severity', models.CharField(choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], max_length=16)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('summary', models.TextField(help_text='Operational description. Never diagnosis/clinical.')),
                ('placed_delivery_on_hold', models.BooleanField(default=False, help_text='True if opening this incident actually transitioned the delivery to INCIDENT_HOLD (only SEVERE/CRITICAL severities do this — see HOLD_SEVERITIES).')),
                ('delivery_status_before_hold', models.CharField(blank=True, help_text='Snapshot of DeliveryRequest.status at the moment this incident placed it on hold, so resolution can restore it. Blank if placed_delivery_on_hold is False.', max_length=32)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_type', models.CharField(blank=True, choices=[('resumed', 'Resumed Normal Delivery'), ('return_to_sender', 'Return to Sender'), ('cancelled', 'Delivery Cancelled'), ('other', 'Other')], max_length=16)),
                ('resolution_note', models.TextField(blank=True, help_text='Required at resolution time — see apps.incidents.services.')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='deliveries.deliveryrequest')),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_opened', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='cargo.package')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('note', 'Note'), ('customer_notified', 'Customer Notified'), ('courier_suspension_review', 'Courier Suspension/Review'), ('escalated', 'Escalated'), ('resolution', 'Resolution')], max_length=32)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_actions', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.incident')),
            ],
            options={
                'ordering': ['incident_id', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('completed', 'Completed')], default='initiated', max_length=16)),
                ('reason', models.TextField()),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_resolutions_completed', to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_resolution', to='deliveries.deliveryrequest')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_resolutions', to='incidents.incident')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_resolutions_initiated', to=settings.AUTH_USER_MODEL)),
                ('return_facility', models.ForeignKey(blank=True, help_text='Where the package is being returned to. Defaults to the original pickup facility if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_resolutions', to='facilities.facility')),
            ],
        ),
    ]
