# Generated by Django 5.2.16 on 2026-08-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='summary',
            field=models.TextField(help_text='Operational description. Never diagnosis/clinical.', max_length=2000),
        ),
    ]
