# Generated by Django 5.2.16 on 2026-08-04 14:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('delivery_status_changed', 'Delivery Status Changed'), ('job_offer_available', 'Job Offer Available'), ('incident_opened', 'Incident Opened'), ('incident_resolved', 'Incident Resolved'), ('invoice_issued', 'Invoice Issued'), ('recipient_link_issued', 'Recipient Tracking Link Issued'), ('credential_expiring', 'Credential Expiring'), ('export_ready', 'Export Ready'), ('generic', 'Generic')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Allow-listed operational identifiers only — see apps.notifications.payload.')),
                ('dedupe_key', models.CharField(blank=True, help_text='Optional caller-supplied key; a second create_notification() call with the same (recipient, notification_type, dedupe_key) returns the existing row instead of creating a duplicate.', max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(blank=True, max_length=254)),
                ('notification_type', models.CharField(choices=[('delivery_status_changed', 'Delivery Status Changed'), ('job_offer_available', 'Job Offer Available'), ('incident_opened', 'Incident Opened'), ('incident_resolved', 'Incident Resolved'), ('invoice_issued', 'Invoice Issued'), ('recipient_link_issued', 'Recipient Tracking Link Issued'), ('credential_expiring', 'Credential Expiring'), ('export_ready', 'Export Ready'), ('generic', 'Generic')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('provider_name', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('mock', 'Mock')], max_length=8)),
                ('correlation_id', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsLogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_label', models.CharField(blank=True, help_text="e.g. 'courier', 'requester' — never a phone number.", max_length=64)),
                ('notification_type', models.CharField(choices=[('delivery_status_changed', 'Delivery Status Changed'), ('job_offer_available', 'Job Offer Available'), ('incident_opened', 'Incident Opened'), ('incident_resolved', 'Incident Resolved'), ('invoice_issued', 'Invoice Issued'), ('recipient_link_issued', 'Recipient Tracking Link Issued'), ('credential_expiring', 'Credential Expiring'), ('export_ready', 'Export Ready'), ('generic', 'Generic')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('message_summary', models.CharField(blank=True, help_text='Short operational text rendered from the allow-listed payload only.', max_length=200)),
                ('provider_name', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('local', 'Local'), ('mock', 'Mock')], max_length=8)),
                ('correlation_id', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='notifications.notification')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(help_text='Documentation only in this phase — never actually called. See WebhookDelivery.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='organizations.organization')),
            ],
            options={
                'ordering': ['organization_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('delivery_status_changed', 'Delivery Status Changed'), ('job_offer_available', 'Job Offer Available'), ('incident_opened', 'Incident Opened'), ('incident_resolved', 'Incident Resolved'), ('invoice_issued', 'Invoice Issued'), ('recipient_link_issued', 'Recipient Tracking Link Issued'), ('credential_expiring', 'Credential Expiring'), ('export_ready', 'Export Ready'), ('generic', 'Generic')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('correlation_id', models.CharField(max_length=64)),
                ('simulated', models.BooleanField(default=True, help_text='Always True in this phase — no real HTTP request is ever made.')),
                ('success', models.BooleanField(default=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.webhookendpoint')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('recipient', 'notification_type', 'dedupe_key'), name='unique_notification_dedupe_key_per_recipient_type'),
        ),
    ]
